build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "Bambu Bridge"
  org.opencontainers.image.source: "https://github.com/thereprocase/bambu-bridge"
