& {
    $ErrorActionPreference = 'Stop'
    # Generated by your Bambu Bridge over owner-authenticated HTTPS.
    # The data contains this printer's native code, never your owner API key.
    $setup = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('__BRIDGE_SETUP_DATA__')) | ConvertFrom-Json

    function Write-OrcaCertificate {
        param([string]$Path, [string]$Certificate)
        $before = [IO.File]::ReadAllBytes($Path)
        $text = [Text.Encoding]::ASCII.GetString($before)
        if (($text -replace '\s','').Contains($Certificate)) { return }
        $der = [Convert]::FromBase64String($Certificate)
        $lines = [Convert]::ToBase64String($der, [Base64FormattingOptions]::InsertLineBreaks)
        $pem = "`n-----BEGIN CERTIFICATE-----`n$lines`n-----END CERTIFICATE-----`n"
        $backup = "$Path.before-bridge-$([Guid]::NewGuid().ToString('N')).bak"
        [IO.File]::WriteAllBytes("$backup.tmp", [byte[]]($before + [Text.Encoding]::ASCII.GetBytes($pem)))
        if (Get-Process -Name 'orca-slicer','OrcaSlicer' -ErrorAction SilentlyContinue) { throw 'Close Orca before continuing.' }
        if ([Convert]::ToBase64String([IO.File]::ReadAllBytes($Path)) -ne [Convert]::ToBase64String($before)) { throw 'Orca certificate file changed. Run setup again.' }
        [IO.File]::Replace("$backup.tmp", $Path, $backup)
        Write-Host "Certificate backup: $backup"
    }

    function Set-OrcaProperty {
        param($Object, [string]$Name, $Value)
        $Object | Add-Member -NotePropertyName $Name -NotePropertyValue $Value -Force
    }

    function Connect-BridgeTls {
        param([int]$Port)
        $expected = $setup.fingerprint
        $check = [Net.Security.RemoteCertificateValidationCallback]{
            param($sender, $certificate, $chain, $errors)
            if ($null -eq $certificate) { return $false }
            $sha = [Security.Cryptography.SHA256]::Create()
            try { $actual = [BitConverter]::ToString($sha.ComputeHash($certificate.GetRawCertData())).Replace('-', '') } finally { $sha.Dispose() }
            return $actual -eq $expected
        }.GetNewClosure()
        $tcp = New-Object Net.Sockets.TcpClient
        $tls = $null
        try {
            if (!$tcp.ConnectAsync($setup.host, $Port).Wait(6000)) { throw 'Connection timed out. Check that Tailscale is connected on this computer.' }
            $tls = New-Object Net.Security.SslStream($tcp.GetStream(), $false, $check)
            $tls.ReadTimeout = 6000
            $tls.WriteTimeout = 6000
            $tls.AuthenticateAsClient($setup.host, $null, [Security.Authentication.SslProtocols]::Tls12, $false)
            return @{ Tcp = $tcp; Tls = $tls }
        } catch {
            if ($tls) { $tls.Dispose() }
            $tcp.Dispose()
            throw
        }
    }

    try {
        Write-Host 'Bambu Bridge: set up Orca on this computer' -ForegroundColor Cyan
        if ($setup.serial -notmatch '^[A-Za-z0-9]{15}$' -or $setup.code -notmatch '^[A-Za-z0-9]{8}$') { throw 'Invalid setup data. Copy a fresh command from the dashboard.' }
        $der = [Convert]::FromBase64String($setup.certificate)
        $sha = [Security.Cryptography.SHA256]::Create()
        try { $fingerprint = [BitConverter]::ToString($sha.ComputeHash($der)).Replace('-', '') } finally { $sha.Dispose() }
        if ($fingerprint -ne $setup.fingerprint) { throw 'Certificate data does not match. Copy a fresh command.' }

        $running = @(Get-Process -Name 'orca-slicer','OrcaSlicer' -ErrorAction SilentlyContinue)
        $exe = $running | Select-Object -First 1 -ExpandProperty Path
        if ($running.Count) {
            Write-Host 'Save your work and close Orca completely.'
            $null = Read-Host 'Press Enter when Orca is closed'
            if (Get-Process -Name 'orca-slicer','OrcaSlicer' -ErrorAction SilentlyContinue) { throw 'Orca is still open. Close it, then run setup again.' }
        }
        $configPath = Join-Path $env:APPDATA 'OrcaSlicer\OrcaSlicer.conf'
        if (!(Test-Path -LiteralPath $configPath)) { throw 'Open Orca once to finish its first-run setup, then close it and run this command again.' }
        $candidates = @()
        if ($exe) { $candidates += Split-Path -Parent $exe }
        $candidates += @("$env:ProgramFiles\OrcaSlicer", "$env:LOCALAPPDATA\Programs\OrcaSlicer", "$env:LOCALAPPDATA\OrcaSlicer")
        $bundle = $null
        foreach ($folder in $candidates) {
            $candidate = Join-Path $folder 'resources\cert\printer.cer'
            if (Test-Path -LiteralPath $candidate) { $bundle = $candidate; break }
        }
        if (!$bundle) {
            Add-Type -AssemblyName System.Windows.Forms
            $pick = New-Object Windows.Forms.OpenFileDialog
            $pick.Title = 'Select orca-slicer.exe in your Orca installation folder'
            $pick.Filter = 'OrcaSlicer|orca-slicer.exe'
            if ($pick.ShowDialog() -ne 'OK') { throw 'No Orca installation selected; nothing changed.' }
            $bundle = Join-Path (Split-Path -Parent $pick.FileName) 'resources\cert\printer.cer'
            $pick.Dispose()
            if (!(Test-Path -LiteralPath $bundle)) { throw 'That folder does not contain Orca printer certificates.' }
        }

        Write-Host '1/3 Checking the bridge and its certificate...'
        $connection = Connect-BridgeTls $setup.mqtt_port
        $connection.Tls.Dispose()
        $connection.Tcp.Dispose()
        $cameraReachable = $false
        try {
            $connection = Connect-BridgeTls $setup.camera_port
            $connection.Tls.Dispose()
            $connection.Tcp.Dispose()
            $cameraReachable = $true
        } catch { Write-Host 'Camera port is not reachable yet. Printer setup will continue; check Tailscale/firewall for the camera port shown in the dashboard.' -ForegroundColor Yellow }

        Write-Host '2/3 Trusting this bridge in Orca...'
        try { Write-OrcaCertificate $bundle $setup.certificate }
        catch {
            $cause = $_.Exception
            while ($cause.InnerException) { $cause = $cause.InnerException }
            if ($cause -isnot [UnauthorizedAccessException]) { throw }
            Write-Host 'Windows needs permission to update Orca in Program Files. Choose Yes in the permission prompt.'
            # Elevate ONLY the public certificate update. The printer code and
            # this user's profile are never sent to the elevated child.
            $publicData = @{ Path = $bundle; Certificate = $setup.certificate } | ConvertTo-Json -Compress
            $publicEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($publicData))
            $functionText = ${function:Write-OrcaCertificate}.ToString()
            $child = '$ErrorActionPreference = ''Stop''; function Write-OrcaCertificate {' + $functionText + '}; try { $d = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(''' + $publicEncoded + ''')) | ConvertFrom-Json; Write-OrcaCertificate $d.Path $d.Certificate; exit 0 } catch { Write-Host $_.Exception.Message; Read-Host ''Press Enter to close''; exit 1 }'
            $encoded = [Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($child))
            $childProcess = Start-Process -FilePath "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -Verb RunAs -ArgumentList @('-NoProfile', '-EncodedCommand', $encoded) -Wait -PassThru
            if ($childProcess.ExitCode -ne 0) { throw 'Certificate update did not finish. Run setup again and allow the Windows permission prompt.' }
        }
        if (!(([IO.File]::ReadAllText($bundle) -replace '\s','').Contains($setup.certificate))) { throw 'Certificate update was not saved. No printer settings were changed.' }

        Write-Host '3/3 Saving the bridge as your Orca printer...'
        if (Get-Process -Name 'orca-slicer','OrcaSlicer' -ErrorAction SilentlyContinue) { throw 'Orca reopened. Close it and run setup again.' }
        $before = [IO.File]::ReadAllBytes($configPath)
        $text = [Text.Encoding]::UTF8.GetString($before).TrimStart([char]0xFEFF)
        $json = $text.Substring(0, $text.LastIndexOf('}') + 1) | ConvertFrom-Json
        foreach ($name in @('local_machines', 'access_code', 'user_access_code')) {
            if ($null -eq $json.$name) { Set-OrcaProperty $json $name ([pscustomobject]@{}) }
            if ($json.$name -isnot [pscustomobject]) { throw "Unexpected Orca format in $name; original config was not changed." }
        }
        $machine = $json.local_machines.($setup.serial)
        if ($null -eq $machine) { $machine = [pscustomobject]@{} }
        if ($machine -isnot [pscustomobject]) { throw 'Unexpected Orca printer format; original config was not changed.' }
        Set-OrcaProperty $machine 'dev_name' 'Bridge P1S'
        Set-OrcaProperty $machine 'dev_ip' $setup.host
        Set-OrcaProperty $machine 'printer_type' 'C12'
        Set-OrcaProperty $json.local_machines $setup.serial $machine
        Set-OrcaProperty $json.access_code $setup.serial $setup.code
        Set-OrcaProperty $json.user_access_code $setup.serial $setup.code
        $body = ($json | ConvertTo-Json -Depth 100) -replace "`r`n", "`n"
        $null = $body | ConvertFrom-Json
        $utf8 = New-Object Text.UTF8Encoding($false)
        $md5 = [Security.Cryptography.MD5]::Create()
        try { $hash = [BitConverter]::ToString($md5.ComputeHash($utf8.GetBytes($body))).Replace('-', '') } finally { $md5.Dispose() }
        $backup = "$configPath.before-bridge-$([Guid]::NewGuid().ToString('N')).bak"
        [IO.File]::WriteAllText("$backup.tmp", "$body`n# MD5 checksum $hash`n", $utf8)
        if (Get-Process -Name 'orca-slicer','OrcaSlicer' -ErrorAction SilentlyContinue) { throw 'Orca reopened. Original config was not changed; run setup again.' }
        if ([Convert]::ToBase64String([IO.File]::ReadAllBytes($configPath)) -ne [Convert]::ToBase64String($before)) { throw 'Orca settings changed during setup; run it again.' }
        [IO.File]::Replace("$backup.tmp", $configPath, $backup)
        Write-Host "Settings backup: $backup"
        Write-Host 'Ready! Open Orca > Device > choose Bridge P1S. Press the camera Play button, then return to the dashboard to check this computer.' -ForegroundColor Green
        if (!$cameraReachable) { Write-Host 'Printer configured; camera network check still needs attention.' -ForegroundColor Yellow }
        Write-Host 'After an Orca update, run a fresh setup command from the dashboard if the connection stops working.'
    } catch {
        Write-Host ('Setup stopped: ' + $_.Exception.Message) -ForegroundColor Red
        Write-Host 'Your existing native access code has not been rotated. Return to the dashboard, correct the issue above, and run setup again.'
    }
}
